Algoritmo "ConversorDeTemperatura"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/09/2024
Var
temperatura : real

Inicio
   leia(temperatura)
   
   temperatura <- (temperatura-32)/1.8
   escreva(temperatura)
   
   

Fimalgoritmo