Algoritmo "MediaPonderada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 16/09/2024
Var
media, nota1 , nota2, nota3,nota4 : real


Inicio
leia(nota1)
leia(nota2)
leia(nota3)
leia(nota4)

media <- (1*nota1 + nota2 * 2 + nota3*3 + nota4*4)/10
escreva(media)


Fimalgoritmo