Algoritmo "OrdemCrescente"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/09/2024
Var
num1 , num2 : real


Inicio

leia(num1)
leia(num2)
se num1 < num2 entao
   escreva(num1," ",num2)
senao
   escreva(num2," ",num1)
fimse


Fimalgoritmo